on:
    push:
    workflow_dispatch: {}
  
name: Semgrep
  
jobs:
    semgrep-scan:
        name: Semgrep Security Scan
        runs-on: ubuntu-latest
        environment: Stage
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Run Semgrep Scan
          uses: pishone-accuknox/semgrep-action@v1.0.4
          with:
            endpoint: ${{ secrets.CSPM_URL }}
            tenant_id: ${{ secrets.TENANT_ID }}
            label: ${{ vars.LABEL_ID }}
            token: ${{ secrets.CSPM_TOKEN }}
            
        - name: Upload Scan Results
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: results
            path: results.json
            retention-days: 5
